# -*- coding: utf-8 -*-
"""bgremoval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ulRCodCNIeds5hG-gU_PtrSfpzOHCZJE
"""

# Install necessary packages
!pip install streamlit rembg Pillow pyngrok

!pip install onnxruntime

!ngrok config add-authtoken $YOUR_AUTHTOKEN

!pip install pyngrok

!ngrok authtoken 2qS7NlV9rOMunH7aBIdTE4TwoQL_3e8pbNVrzem8WSPAiRErn

!pip install rembg
!pip install onnxruntime

!ngrok authtoken 2qS7NlV9rOMunH7aBIdTE4TwoQL_3e8pbNVrzem8WSPAiRErn

!pip install --upgrade pyngrok

#please go on ngrok website to create a token for the localhost to run
# Install necessary packages
!pip install streamlit rembg Pillow pyngrok
from pyngrok import ngrok
# Import required libraries
import streamlit as st
from rembg import remove
from PIL import Image
from io import BytesIO
import base64
from pyngrok import ngrok

# Streamlit code
st.set_page_config(layout='wide', page_title="Image Background Remover")
st.write("## Remove Background from Image")
st.write(
    ":dog: Try Uploading an image to watch the background magically removed. Full quality images can be downloaded from the sidebar:grin:"
)
st.sidebar.write("## Upload and Download :gear:")

# Setting max file size
MAX_FILE_SIZE = 5*1024*1024  # 5 MB

# Function to convert image
def convert_image(img):
    buf = BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()

# Function to fix and display image
def fix_img(upload):
    image = Image.open(upload)
    col1, col2 = st.columns(2)
    col1.write("Original Image :camera:")
    col1.image(image)

    fixed = remove(image)
    col2.write("Fixed Image :wrench:")
    col2.image(fixed)

    st.sidebar.markdown("\n")
    st.sidebar.download_button("Download Fixed Image", convert_image(fixed), "fixed.png", "image/png")

# File uploader
my_upload = st.sidebar.file_uploader("Upload an Image", type=["png", "jpg", "jpeg"])

if my_upload is not None:
    if my_upload.size > MAX_FILE_SIZE:
        st.error("The file is too large. Please select a file less than 5MB")
    else:
        fix_img(my_upload)
else:
    st.warning("Please upload an image to begin.")


# Set up ngrok and start a tunnel
public_url = ngrok.connect(8501)
print(f"Ngrok tunnel URL: {public_url}")

